### ISSUE TITLE
illumina design studio amplicon seq question

### ISSUE THREAD

**Issue by joowkim** [crukci-bioinformatics/ampliconseq#2]
Hello,

Thanks for the great workflow. I'm about to test the tool but wanted to know that if it is okay to exclude `AmpliconStart` and `AmpliconEnd` (not avail for us)

Is there any work around for this? Or would it be okay if I add some arbitrary bps for primer sequences and try it?

Best,
JKim

**Comment by eldrid01** [comment]
Hi joowkim,

Yes, I think that adding/subtracting 22 (or so) bases from the target start and end coordinates would be worth trying but you will need to be more lenient with matching sequences to amplicons by increasing the maxDistanceFromAmpliconEnd parameter. By default it is set to 0 which means that only read pairs that align precisely at the amplicon start and end coordinates are taken forward for variant calling, but you might want to increase this, say to 2 or 3 to account for amplicons where the primer sequence was a bit shorter or longer than 22 bases. It appears that this is not a documented parameter, mainly because the primer sequences are known for all our amplicon panels.

An alternative would be to look at where your reads line up on the genome, e.g. by looking at your target regions in IGV. You should see big blocks of many read pairs all aligning to the same locations at the amplicon start and end coordinates. This is probably not practical if you have several amplicons though.

Hope that helps,
Matt

**Comment by joowkim** [comment]
Hi Matt,

Thanks for the suggestions. Will try!
